server:
  port: 8065

spring:
  jpa:
    hbm2ddl:
      auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false
    username: smart
    password:
    driver-class-name: com.mysql.jdbc.Driver


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

